# Generated by Django 3.2 on 2021-05-13 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210513_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='is_full_screen_size',
        ),
        migrations.AlterField(
            model_name='picture',
            name='is_card_size',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Изображение карточки товара'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Изображение опубликовано'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='products.Tag', verbose_name='Теги'),
        ),
    ]
